logging:
    level:
        root: INFO
        org.springframework.jdbc: DEBUG
        org.hibernate.SQL: DEBUG

spring:
    application:
        name: uau-mart

    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true

    sql:
        init:
            mode: always

